package edu.cwru.SimpleRTS.action;

public enum ActionType {
	PRIMATIVEMOVE, PRIMATIVEATTACK, PRIMATIVEGATHER, PRIMATIVEBUILD, PRIMATIVEPRODUCE, PRIMATIVEUPGRADE,
	COMPOUNDMOVE, COMPOUNDATTACK, COMPOUNDGATHER, COMPOUNDBUILD, COMPOUNDPRODUCE, COMPOUNDUPGRADE;
}
