package edu.cwru.SimpleRTS.action;

public enum ActionType {
	PRIMITIVEMOVE, PRIMITIVEATTACK, PRIMITIVEGATHER, PRIMITIVEDEPOSIT, PRIMITIVEBUILD, PRIMITIVEPRODUCE, 
	COMPOUNDMOVE, COMPOUNDATTACK, COMPOUNDGATHER, COMPOUNDDEPOSIT, COMPOUNDBUILD, COMPOUNDPRODUCE;
}
