package edu.cwru.SimpleRTS.action;

public enum ActionType {
	PRIMITIVEMOVE, PRIMITIVEATTACK, PRIMITIVEGATHER, PRIMITIVEBUILD, PRIMITIVEPRODUCE, PRIMITIVEUPGRADE,
	COMPOUNDMOVE, COMPOUNDATTACK, COMPOUNDGATHER, COMPOUNDBUILD, COMPOUNDPRODUCE, COMPOUNDUPGRADE;
}
