//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.10 at 09:32:36 PM EDT 
//


package edu.cwru.sepia.util.config.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.cwru.sepia.util.config.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.cwru.sepia.util.config.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlAgentParameters }
     * 
     */
    public XmlAgentParameters createXmlAgentParameters() {
        return new XmlAgentParameters();
    }

    /**
     * Create an instance of {@link XmlConfiguration }
     * 
     */
    public XmlConfiguration createXmlConfiguration() {
        return new XmlConfiguration();
    }

    /**
     * Create an instance of {@link XmlModelParameters }
     * 
     */
    public XmlModelParameters createXmlModelParameters() {
        return new XmlModelParameters();
    }

    /**
     * Create an instance of {@link XmlRunner }
     * 
     */
    public XmlRunner createXmlRunner() {
        return new XmlRunner();
    }

    /**
     * Create an instance of {@link XmlKeyValuePair }
     * 
     */
    public XmlKeyValuePair createXmlKeyValuePair() {
        return new XmlKeyValuePair();
    }

    /**
     * Create an instance of {@link XmlAgentParameters.AgentClass }
     * 
     */
    public XmlAgentParameters.AgentClass createXmlAgentParametersAgentClass() {
        return new XmlAgentParameters.AgentClass();
    }

}
